---
name: CI


on:
  push:
    branches:
      - main
    # TODO remove `branches:` and uncomment below
    # branches-ignore:
    #   - master
    #   - main
    #   - mainline
    #   - rb/*


permissions:
  contents: read
  security-events: write


env:
  IMAGE_NAME: nginx-brotli-poc


jobs:
  build-version-list:
    runs-on: ubuntu-latest
    outputs:
      nginx_versions: ${{ steps.nginx_versions.outputs.nginx_versions }}
    steps:
      - uses: actions/checkout@v6

      - name: Read nginx versions
        id: nginx_versions
        run: |
          (
            echo -n "nginx_versions="
            jq -R -s -c '[split("\n")[]|select(. | length > 0)]' < versions.txt
          ) >> "$GITHUB_OUTPUT"


  build-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nginx_version: ${{ fromJson(needs.build-version-list.outputs.nginx_versions) }}
    needs: build-version-list

    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4.2.0

      - name: Build builder-base image
        uses: docker/build-push-action@v7.3.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/amd64
          target: builder-base
          build-args: |
            NGINX_VERSION=${{ matrix.nginx_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nginx_version: ${{ fromJson(needs.build-version-list.outputs.nginx_versions) }}
    needs:
      - build-version-list
      - build-base

    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4.2.0

      - name: Build amd64 image
        uses: docker/build-push-action@v7.3.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/amd64
          build-args: |
            NGINX_VERSION=${{ matrix.nginx_version }}
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.nginx_version }}
          # output to docker so we can test in next step
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test
        run: |
          docker run --rm -v $(pwd)/tests/tests.sh:/tests.sh --entrypoint sh ${{ env.IMAGE_NAME }}:${{ matrix.nginx_version }} /tests.sh

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ matrix.nginx_version }}
          exit-code: '1' # This will fail the pipeline if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
