---
name: CI


on:
  push:
    branches-ignore:
      - master
      - main

  pull_request:
    branches-ignore:
      - master
      - main
  workflow_dispatch:
    inputs:
      pr_sha:
        description: 'The exact head SHA of the PR commit'
        required: false
        type: string
        default: ""


env:
  IMAGE_NAME: nginx-brotli-poc


jobs:
  set-pr-status-in-progress:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.pr_sha != ''
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Create GitHub Check Run
        run: |
          gh api --method POST /repos/${{ github.repository }}/statuses/${{ github.event.inputs.pr_sha }} \
            -f state="pending" \
            -f context="CI" \
            -f description="Running automated workflows..." \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  build-version-list:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      nginx_versions: ${{ steps.nginx_versions.outputs.nginx_versions }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Read nginx versions
        id: nginx_versions
        run: python ci/getVersionsForCi.py


  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4.2.0

      - name: Build builder-base image
        uses: docker/build-push-action@v7.3.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/amd64
          target: builder-base
          cache-from: type=gha
          cache-to: type=gha,mode=max


  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        nginx_version: ${{ fromJson(needs.build-version-list.outputs.nginx_versions) }}
    needs:
      - build-version-list
      - build-base
      - set-pr-status-in-progress

    steps:
      - uses: actions/checkout@v7

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4.2.0

      - name: Build amd64 image
        uses: docker/build-push-action@v7.3.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/amd64
          build-args: |
            NGINX_VERSION=${{ matrix.nginx_version }}
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.nginx_version }}
          # output to docker so we can test in next step
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test
        run: |
          docker run --rm -v $(pwd)/tests/tests.sh:/tests.sh --entrypoint sh ${{ env.IMAGE_NAME }}:${{ matrix.nginx_version }} /tests.sh

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ matrix.nginx_version }}
          exit-code: '1' # This will fail the pipeline if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  update-ci-status:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    needs:
      - build-and-test
      - set-pr-status-in-progress
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.pr_sha != '' && always()
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Update GitHub Check Run
        run: |
          if [ "${{ needs.build-and-test.result }}" = "success" ]; then
            STATE="success"
            DESC="All integration tests passed successfully!"
          else
            STATE="failure"
            DESC="Integration tests failed. Check logs."
          fi

          gh api --method POST /repos/${{ github.repository }}/statuses/${{ github.event.inputs.pr_sha }} \
            -f state="$STATE" \
            -f context="CI" \
            -f description="$DESC" \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
